Add new status flag "remotepaths" to display the remote path of each …
wtsi-hgi/ibackup pull request #71
Opened 2024-11-19 15:58 UTC by rk1274

…file

2024-11-20 14:56 UTC, mjkw31 submitted a review, later dismissed
LGTM.

2024-11-20 18:35 UTC, sb10 requested changes
Nicely done, thanks. Just some tweaks to improve the behaviour please.

2024-11-20 18:35 UTC, sb10 commented on cmd/status.go
> +		cols = append(cols, "Remote Path")
It would work better if it was the second column after Path, and if Path was renamed "Local Path" for clarity.

2024-11-20 18:35 UTC, sb10 commented on cmd/status.go
> +			warn("your transformer didn't work: %s", err)
This should probably just die, and then you don't have to return and supply the warnedAbout bool.

2024-11-21 12:59 UTC, sb10 approved these changes

2024-11-21 13:00 UTC, merged