Rename cmd getremote to list and add flags --local and --remote
wtsi-hgi/ibackup pull request #73
Opened 2024-11-22 14:49 UTC by rk1274

Refactor list to output both local and remote paths if no flag is provided

2024-11-22 14:57 UTC, mjkw31 submitted a review, later dismissed
LGTM.

2024-11-22 15:50 UTC, sb10 requested changes

2024-11-22 15:50 UTC, sb10 commented on cmd/list.go
> +		"get local paths only for the set with this name")
only get local paths for the --name'd set

Likewise for remote option

2024-11-25 09:08 UTC, sb10 approved these changes

2024-11-25 09:08 UTC, merged